src/Entity/Produit.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ProduitRepository")
 */
class Produit
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Nom;

    /**
     * @ORM\Column(type="text")
     */
    private $Description;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $image;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $prix;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->Nom;
    }

    public function setNom(string $Nom): self
    {
        $this->Nom = $Nom;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->Description;
    }

    public function setDescription(string $Description): self
    {
        $this->Description = $Description;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(?string $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function getPrix(): ?float
    {
        return $this->prix;
    }

    public function setPrix(?float $prix): self
    {
        $this->prix = $prix;

        return $this;
    }
}

src/Form/ProduitType.php
<?php

namespace App\Form;

use App\Entity\Produit;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ProduitType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('Nom')
            ->add('Description')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Produit::class,
        ]);
    }
}

src/Controller/ProduitController.php
<?php

namespace App\Controller;

use App\Entity\Produit;
use App\Form\ProduitType;
use App\Repository\ProduitRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/produit")
 */
class ProduitController extends AbstractController
{
    /**
     * @Route("/", name="produit_vue", methods={"GET"})
     */
    public function index(ProduitRepository $produitRepository): Response
    {
        $produit = $produitRepository->findAll();
        return $this->render('produit/vue.html.twig', [
            'produit' => $produit,
        ]);
    }

    /**
     * @Route("/admin", name="produit_admin", methods={"GET"})
     */
    public function admin(ProduitRepository $produitRepository): Response
    {
        $produit = $produitRepository->findAll();
        return $this->render('produit/index.html.twig', [
            'produit' => $produit,
        ]);
    }

    /**
     * @Route("/new", name="produit_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $produit = new Produit();
        $form = $this->createForm(ProduitType::class, $produit);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($produit);
            $entityManager->flush();

            return $this->redirectToRoute('produit_admin');
        }

        return $this->render('produit/new.html.twig', [
            'produit' => $produit,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="produit_show", methods={"GET"})
     */
    public function show(Produit $produit): Response
    {
        return $this->render('produit/show.html.twig', [
            'produit' => $produit,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="produit_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Produit $produit): Response
    {
        $form = $this->createForm(ProduitType::class, $produit);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('produit_admin');
        }

        return $this->render('produit/edit.html.twig', [
            'produit' => $produit,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="produit_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Produit $produit): Response
    {
        if ($this->isCsrfTokenValid('delete'.$produit->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($produit);
            $entityManager->flush();
        }

        return $this->redirectToRoute('produit_admin');
    }
}

templates/produit/_delete_form.html.twig
<form method="post" action="{{ path('produit_delete', {'id': produit.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ produit.id) }}">
    <button class="btn">Delete</button>
</form>

templates/produit/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/produit/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Produit{% endblock %}

{% block body %}
    <h1>Edit Produit</h1>

    {{ include('produit/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('produit_admin') }}">back to list</a>

    {{ include('produit/_delete_form.html.twig') }}
{% endblock %}

templates/produit/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Produit index{% endblock %}

{% block body %}
    <h1>Produit index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Title</th>
                <th>Paragraph</th>
                <th>Ordering</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for produit in produit %}
            <tr>
                <td>{{ produit.id }}</td>
                <td>{{ produit.nom }}</td>
                <td>{{ produit.image }}</td>
                <td>{{ produit.prix }}</td>
                <td>{{ produit.description }}</td>
                <td>
                    <a href="{{ path('produit_show', {'id': produit.id}) }}">show</a>
                    <a href="{{ path('produit_edit', {'id': produit.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="5">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('produit_new') }}">Create new</a>
{% endblock %}

templates/produit/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Produit{% endblock %}

{% block body %}
    <h1>Create new Produit</h1>

    {{ include('produit/_form.html.twig') }}

    <a href="{{ path('produit_admin') }}">back to list</a>
{% endblock %}

templates/produit/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Produit{% endblock %}

{% block body %}
    <h1>Produit</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ produit.id }}</td>
            </tr>
            <tr>
                <th>Nom</th>
                <td>{{ produit.Nom }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ produit.Description }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('produit_admin') }}">back to list</a>

    <a href="{{ path('produit_edit', {'id': produit.id}) }}">edit</a>

    {{ include('produit/_delete_form.html.twig') }}
{% endblock %}

templates/produit/vue.html.twig
{% extends 'base.html.twig' %}

{% block title %}Produit index{% endblock %}

{% block body %}
 <section id="ancre_produit" class="service-section">
        <h1 class="produit_title">Mes produits</h1>
        <div class="cards-container">
            {% for produit in produit %}
                <div class="produit-card">
                    <h2 class="produit_subtitle">{{produit.nom}}</h2>
                    <img src="../image/{{produit.image}}" class="produit_img" alt="illustration">
                    <p class="produit-detail">{{produit.prix}}</p>    
                    <p class="produit-detail">{{produit.description}}</p>    
                </div>
            {% endfor %}
        </div>
    </section>
{% endblock %}